-- Never Have I Ever Statements Seed Data

-- PG CATEGORY (25 statements)
INSERT INTO never_have_i_ever_statements (statement, category) VALUES
('Never have I ever lied to get out of plans', 'pg'),
('Never have I ever pretended to be sick', 'pg'),
('Never have I ever stalked someone on social media', 'pg'),
('Never have I ever forgotten someone''s name right after meeting them', 'pg'),
('Never have I ever laughed at the wrong moment', 'pg'),
('Never have I ever cried during a movie', 'pg'),
('Never have I ever sung in the shower', 'pg'),
('Never have I ever talked to myself', 'pg'),
('Never have I ever googled myself', 'pg'),
('Never have I ever re-gifted something', 'pg'),
('Never have I ever pretended to understand something I didn''t', 'pg'),
('Never have I ever fallen asleep during a movie', 'pg'),
('Never have I ever sent a text to the wrong person', 'pg'),
('Never have I ever walked into a glass door', 'pg'),
('Never have I ever waved at someone who wasn''t waving at me', 'pg'),
('Never have I ever tripped in public', 'pg'),
('Never have I ever forgotten my own birthday', 'pg'),
('Never have I ever eaten food that fell on the floor', 'pg'),
('Never have I ever worn mismatched socks on purpose', 'pg'),
('Never have I ever binge-watched an entire series in one day', 'pg'),
('Never have I ever taken a selfie in a public bathroom', 'pg'),
('Never have I ever pretended to be on the phone to avoid someone', 'pg'),
('Never have I ever checked my phone during a conversation', 'pg'),
('Never have I ever judged someone by their music taste', 'pg'),
('Never have I ever made up an excuse to leave early', 'pg');

-- FUNNY CATEGORY (25 statements)  
INSERT INTO never_have_i_ever_statements (statement, category) VALUES
('Never have I ever tried to look cool and failed miserably', 'funny'),
('Never have I ever laughed so hard I cried', 'funny'),
('Never have I ever snorted while laughing', 'funny'),
('Never have I ever made an embarrassing autocorrect mistake', 'funny'),
('Never have I ever walked into the wrong bathroom', 'funny'),
('Never have I ever waved back at someone waving at the person behind me', 'funny'),
('Never have I ever pretended to know a song and hummed along', 'funny'),
('Never have I ever danced like nobody was watching (but they were)', 'funny'),
('Never have I ever tried to take a cute photo and looked terrible', 'funny'),
('Never have I ever laughed at my own joke when nobody else did', 'funny'),
('Never have I ever accidentally liked an old photo while stalking', 'funny'),
('Never have I ever walked into a pole or sign while texting', 'funny'),
('Never have I ever tried to play it cool after tripping', 'funny'),
('Never have I ever made weird faces in the mirror', 'funny'),
('Never have I ever talked to an animal like it could understand me', 'funny'),
('Never have I ever practiced conversations in my head', 'funny'),
('Never have I ever made sound effects while doing something', 'funny'),
('Never have I ever pretended to be asleep to avoid doing something', 'funny'),
('Never have I ever eaten something weird just to try it', 'funny'),
('Never have I ever made up a word and used it confidently', 'funny');

-- DEEP CATEGORY (25 statements)
INSERT INTO never_have_i_ever_statements (statement, category) VALUES
('Never have I ever questioned my life choices', 'deep'),
('Never have I ever felt like an imposter', 'deep'),
('Never have I ever had a crush on a friend', 'deep'),
('Never have I ever kept a secret from my best friend', 'deep'),
('Never have I ever regretted something I said', 'deep'),
('Never have I ever felt jealous of a friend''s success', 'deep'),
('Never have I ever pretended to be happy when I wasn''t', 'deep'),
('Never have I ever ghosted someone', 'deep'),
('Never have I ever judged someone unfairly', 'deep'),
('Never have I ever had feelings for two people at once', 'deep'),
('Never have I ever lied to protect someone''s feelings', 'deep'),
('Never have I ever felt like I didn''t belong', 'deep'),
('Never have I ever compared myself to others', 'deep'),
('Never have I ever had a falling out with a close friend', 'deep'),
('Never have I ever felt misunderstood', 'deep'),
('Never have I ever questioned a friendship', 'deep'),
('Never have I ever felt left out', 'deep'),
('Never have I ever had trust issues', 'deep'),
('Never have I ever felt like giving up', 'deep'),
('Never have I ever wished I could start over', 'deep'),
('Never have I ever felt guilty about something small', 'deep'),
('Never have I ever overthought a simple situation', 'deep'),
('Never have I ever felt anxious about the future', 'deep'),
('Never have I ever doubted myself', 'deep'),
('Never have I ever felt lonely in a crowd', 'deep');

-- ADULT CATEGORY (25 statements)
INSERT INTO never_have_i_ever_statements (statement, category) VALUES
('Never have I ever lied on my resume', 'adult'),
('Never have I ever called in sick when I wasn''t', 'adult'),
('Never have I ever snooped through someone''s phone', 'adult'),
('Never have I ever read someone''s diary or messages', 'adult'),
('Never have I ever pretended to like a gift I hated', 'adult'),
('Never have I ever badmouthed someone behind their back', 'adult'),
('Never have I ever broken a promise', 'adult'),
('Never have I ever cheated on a test or exam', 'adult'),
('Never have I ever stolen something', 'adult'),
('Never have I ever lied to my parents about where I was', 'adult'),
('Never have I ever faked being busy to avoid someone', 'adult'),
('Never have I ever spread a rumor', 'adult'),
('Never have I ever eavesdropped on a private conversation', 'adult'),
('Never have I ever pretended to forget something on purpose', 'adult'),
('Never have I ever manipulated a situation to my advantage', 'adult'),
('Never have I ever taken credit for someone else''s work', 'adult'),
('Never have I ever lied about my age', 'adult'),
('Never have I ever faked an emotion', 'adult'),
('Never have I ever judged someone by their appearance', 'adult'),
('Never have I ever held a grudge', 'adult');

SELECT category, COUNT(*) as count FROM never_have_i_ever_statements GROUP BY category;
