-- Part 2: Friends Extreme + Couples Mode Questions
-- Run this AFTER replace-all-questions.sql

-- ============================================
-- FRIENDS MODE - EXTREME DARES (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('dare', 'extreme', 'Send your wildest selfie (with consent).', 'friends'),
('dare', 'extreme', 'Serenade someone in the group.', 'friends'),
('dare', 'extreme', 'Text your crush a flirty "hey."', 'friends'),
('dare', 'extreme', 'Share something you wouldn''t admit IRL.', 'friends'),
('dare', 'extreme', 'Share your most awkward romantic photo.', 'friends'),
('dare', 'extreme', 'Send a voice note confessing a secret crush.', 'friends'),
('dare', 'extreme', 'Reenact a steamy movie scene on video.', 'friends'),
('dare', 'extreme', 'Pretend to have a crush on someone in the group.', 'friends'),
('dare', 'extreme', 'Send a dramatic love confession.', 'friends'),
('dare', 'extreme', 'Do a playful striptease (keep it safe and tasteful).', 'friends'),
('dare', 'extreme', 'Share a daring fantasy.', 'friends'),
('dare', 'extreme', 'Text your last ex something funny.', 'friends'),
('dare', 'extreme', 'Draw a kiss mark on your hand and show it.', 'friends'),
('dare', 'extreme', 'Share your most embarrassing text message.', 'friends'),
('dare', 'extreme', 'Write a raunchy limerick.', 'friends'),
('dare', 'extreme', 'Give a virtual "lap dance" on camera.', 'friends'),
('dare', 'extreme', 'Send a bold flirty message to a stranger.', 'friends'),
('dare', 'extreme', 'Do your best seductive dance.', 'friends'),
('dare', 'extreme', 'Send a sultry selfie (always optional).', 'friends'),
('dare', 'extreme', 'Make a video pretending to blush.', 'friends'),
('dare', 'extreme', 'Read a naughty text in a dramatic voice.', 'friends'),
('dare', 'extreme', 'Act like you just got caught flirting.', 'friends'),
('dare', 'extreme', 'Share your "hidden" love song playlist.', 'friends'),
('dare', 'extreme', 'Pretend to be your crush on video.', 'friends'),
('dare', 'extreme', 'Write a steamy text, share redacted version.', 'friends'),
('dare', 'extreme', 'Send a picture of your wildest hair day.', 'friends'),
('dare', 'extreme', 'Make an over-the-top romantic speech.', 'friends'),
('dare', 'extreme', 'Share an intimate secret (optional).', 'friends'),
('dare', 'extreme', 'Recite a raunchy poem.', 'friends'),
('dare', 'extreme', 'Do 5 sexy poses and share best one.', 'friends'),
('dare', 'extreme', 'Make a flirty pickup line video.', 'friends'),
('dare', 'extreme', 'Record a moan (funny or real).', 'friends'),
('dare', 'extreme', 'Tell about your weirdest crush.', 'friends'),
('dare', 'extreme', 'Send a "goodnight" kiss video.', 'friends'),
('dare', 'extreme', 'Do a dramatic hair toss.', 'friends'),
('dare', 'extreme', 'Share a photo of your wildest outfit.', 'friends'),
('dare', 'extreme', 'Whisper your best flirt move.', 'friends'),
('dare', 'extreme', 'Act out a flirt fight scene.', 'friends'),
('dare', 'extreme', 'Share something you regret saying to a crush.', 'friends'),
('dare', 'extreme', 'Send a daring selfie with filters.', 'friends'),
('dare', 'extreme', 'Share the last thing you searched in private.', 'friends'),
('dare', 'extreme', 'Pretend you''re writing a hot text.', 'friends'),
('dare', 'extreme', 'Send a video of blowing a kiss.', 'friends'),
('dare', 'extreme', 'Tell a story involving an awkward date.', 'friends'),
('dare', 'extreme', 'Share your "cringe" romantic moment.', 'friends'),
('dare', 'extreme', 'Give a sultry stare into the camera.', 'friends'),
('dare', 'extreme', 'Share your favorite romantic emoji streak.', 'friends'),
('dare', 'extreme', 'Act like a lovesick puppy.', 'friends'),
('dare', 'extreme', 'Send a photo of your best pout.', 'friends'),
('dare', 'extreme', 'Pretend to be shy and embarrassed.', 'friends'),
('dare', 'extreme', 'Do a dramatic love sigh.', 'friends'),
('dare', 'extreme', 'Tell the group about your worst love advice.', 'friends'),
('dare', 'extreme', 'Share an awkward hug story.', 'friends'),
('dare', 'extreme', 'Write a flirty chat line.', 'friends'),
('dare', 'extreme', 'Send a romantic quote you like.', 'friends'),
('dare', 'extreme', 'Whisper "I''m yours" dramatically.', 'friends'),
('dare', 'extreme', 'Make a funny romantic pun.', 'friends'),
('dare', 'extreme', 'Act out a smitten crush.', 'friends'),
('dare', 'extreme', 'Pretend you''re lost in someone''s eyes.', 'friends'),
('dare', 'extreme', 'Share a wild romantic daydream.', 'friends');

-- ============================================
-- FRIENDS MODE - EXTREME TRUTHS (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('truth', 'extreme', 'What''s the wildest secret you''ve never told anyone?', 'friends'),
('truth', 'extreme', 'Describe your most intense romantic fantasy.', 'friends'),
('truth', 'extreme', 'Have you ever had a secret crush on someone here?', 'friends'),
('truth', 'extreme', 'What''s the most scandalous photo you''ve taken?', 'friends'),
('truth', 'extreme', 'Have you ever sent or received explicit pictures?', 'friends'),
('truth', 'extreme', 'What''s the most adventurous place you''ve been intimate?', 'friends'),
('truth', 'extreme', 'Have you ever been caught doing something intimate?', 'friends'),
('truth', 'extreme', 'What''s a secret kink or desire you have?', 'friends'),
('truth', 'extreme', 'Have you ever lied about your sexual experience?', 'friends'),
('truth', 'extreme', 'What''s your wildest hookup story?', 'friends'),
('truth', 'extreme', 'Have you ever been in an open relationship?', 'friends'),
('truth', 'extreme', 'What''s the most taboo thing you''ve done?', 'friends'),
('truth', 'extreme', 'Have you ever used a fake name or identity online?', 'friends'),
('truth', 'extreme', 'What''s the most intense dare you''ve ever completed?', 'friends'),
('truth', 'extreme', 'Have you ever cheated on a partner?', 'friends'),
('truth', 'extreme', 'What''s a confession you''re scared to admit even here?', 'friends'),
('truth', 'extreme', 'What''s the most risque text you''ve sent?', 'friends'),
('truth', 'extreme', 'Have you ever fantasized about someone in this group?', 'friends'),
('truth', 'extreme', 'What turns you on the most?', 'friends'),
('truth', 'extreme', 'What''s a secret someone here doesn''t know about you?', 'friends'),
('truth', 'extreme', 'Have you ever had a one-night stand?', 'friends'),
('truth', 'extreme', 'What''s something you''d never do again?', 'friends'),
('truth', 'extreme', 'Have you ever lied to a partner about your feelings?', 'friends'),
('truth', 'extreme', 'What''s your biggest regret in love or sex?', 'friends'),
('truth', 'extreme', 'Have you ever been caught spying on a partner?', 'friends'),
('truth', 'extreme', 'What''s the most embarrassing intimate moment?', 'friends'),
('truth', 'extreme', 'Have you ever been jealous in a relationship?', 'friends'),
('truth', 'extreme', 'What''s your secret desire that you''re afraid to admit?', 'friends'),
('truth', 'extreme', 'Have you ever had a steamy dream about someone here?', 'friends'),
('truth', 'extreme', 'What''s your wildest fantasy involving an ex?', 'friends'),
('truth', 'extreme', 'Have you ever sent an explicit video or photo?', 'friends'),
('truth', 'extreme', 'What''s the most scandalous place you''ve been intimate?', 'friends'),
('truth', 'extreme', 'Have you ever cheated emotionally?', 'friends'),
('truth', 'extreme', 'What''s your biggest fear about relationships?', 'friends'),
('truth', 'extreme', 'Have you ever pretended to like something for a partner?', 'friends'),
('truth', 'extreme', 'What''s the most daring thing you''ve done for love?', 'friends'),
('truth', 'extreme', 'Have you ever lied about being single?', 'friends'),
('truth', 'extreme', 'What''s something intimate you wish more people knew about you?', 'friends'),
('truth', 'extreme', 'Have you ever fantasized about someone off limits?', 'friends'),
('truth', 'extreme', 'What''s your "guilty pleasure" in relationships?', 'friends'),
('truth', 'extreme', 'Have you ever wanted to be someone else''s partner?', 'friends'),
('truth', 'extreme', 'What''s the most embarrassing thing you''ve done in front of a crush?', 'friends'),
('truth', 'extreme', 'Have you ever lied to get out of a date?', 'friends'),
('truth', 'extreme', 'What''s a secret desire you''d try if safe?', 'friends'),
('truth', 'extreme', 'Have you ever flirted with the wrong person?', 'friends'),
('truth', 'extreme', 'What''s something no one here would guess about your love life?', 'friends'),
('truth', 'extreme', 'Have you ever broken someone''s heart?', 'friends'),
('truth', 'extreme', 'What''s the naughtiest thought you''ve had recently?', 'friends'),
('truth', 'extreme', 'Have you ever been caught sneaking around?', 'friends'),
('truth', 'extreme', 'What''s the wildest intimate dare you''d accept?', 'friends'),
('truth', 'extreme', 'Have you ever pretended to be interested in someone?', 'friends'),
('truth', 'extreme', 'What''s your secret fantasy you''re too embarrassed to say?', 'friends'),
('truth', 'extreme', 'Have you ever flirted with a friend''s partner?', 'friends'),
('truth', 'extreme', 'What''s the creepiest thing you''ve done for love?', 'friends'),
('truth', 'extreme', 'Have you ever had a crush you can''t forget?', 'friends');
