-- Part 5: Couples Mode - Spicy Questions
-- Run this to add Couples Spicy Dares and Truths

-- ============================================
-- COUPLES MODE - SPICY DARES (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('dare', 'spicy', 'Send a flirty message to the last person you DM''ed.', 'couples'),
('dare', 'spicy', 'Compliment someone flirtatiously in chat.', 'couples'),
('dare', 'spicy', 'Post a "cringe" status update.', 'couples'),
('dare', 'spicy', 'Share a funny pick-up line on social media.', 'couples'),
('dare', 'spicy', 'Whisper a secret fantasy in chat.', 'couples'),
('dare', 'spicy', 'Send a GIF that best describes your love life.', 'couples'),
('dare', 'spicy', 'Record a cheeky voice note.', 'couples'),
('dare', 'spicy', 'Share a selfie with your wildest hair.', 'couples'),
('dare', 'spicy', 'Pretend to be a famous lover for a round.', 'couples'),
('dare', 'spicy', 'Reenact a movie kiss scene.', 'couples'),
('dare', 'spicy', 'Change your profile pic to a funny romantic one for 24h.', 'couples'),
('dare', 'spicy', 'Send a voice note acting shy.', 'couples'),
('dare', 'spicy', 'Tell a spicy joke.', 'couples'),
('dare', 'spicy', 'Text "I can''t stop thinking about you" to a friend (screen off).', 'couples'),
('dare', 'spicy', 'Make a mock dramatic love confession.', 'couples'),
('dare', 'spicy', 'Share a screenshot of your chat crush (if comfortable).', 'couples'),
('dare', 'spicy', 'Do a flirty dance on camera.', 'couples'),
('dare', 'spicy', 'Act out a romantic movie breakup scene.', 'couples'),
('dare', 'spicy', 'Send a selfie biting your lip.', 'couples'),
('dare', 'spicy', 'Write a flirty tongue twister.', 'couples'),
('dare', 'spicy', 'Sing a love song badly on video.', 'couples'),
('dare', 'spicy', 'Name your favorite body part on a partner.', 'couples'),
('dare', 'spicy', 'Pretend to propose via chat.', 'couples'),
('dare', 'spicy', 'Share your weirdest date story.', 'couples'),
('dare', 'spicy', 'Do a playful seductive wink.', 'couples'),
('dare', 'spicy', 'Tell a romantic lie.', 'couples'),
('dare', 'spicy', 'Write a poem about a crush.', 'couples'),
('dare', 'spicy', 'Send a voice note blowing a kiss.', 'couples'),
('dare', 'spicy', 'Say a naughty phrase in a funny voice.', 'couples'),
('dare', 'spicy', 'Share your dream romantic getaway.', 'couples'),
('dare', 'spicy', 'Act like a cat flirting.', 'couples'),
('dare', 'spicy', 'Share your best "I''m interested" look photo.', 'couples'),
('dare', 'spicy', 'Write a text as if you''re seducing someone.', 'couples'),
('dare', 'spicy', 'Do 10 sexy stretches.', 'couples'),
('dare', 'spicy', 'Send a photo with lip gloss or kiss mark.', 'couples'),
('dare', 'spicy', 'Speak in a flirty language (real or made-up).', 'couples'),
('dare', 'spicy', 'Send a cute emoji combo to someone.', 'couples'),
('dare', 'spicy', 'Pretend you''re on a date in Paris.', 'couples'),
('dare', 'spicy', 'Make seductive sound effects.', 'couples'),
('dare', 'spicy', 'Name 3 ways you''d impress someone.', 'couples'),
('dare', 'spicy', 'Share your crush''s name with emojis only.', 'couples'),
('dare', 'spicy', 'Write a "Dear Diary" flirty entry.', 'couples'),
('dare', 'spicy', 'Recite a love poem from memory (or make one up).', 'couples'),
('dare', 'spicy', 'Send a selfie pretending to swoon.', 'couples'),
('dare', 'spicy', 'Compliment a player''s smile in a flirty way.', 'couples'),
('dare', 'spicy', 'Share your favorite romantic app or game.', 'couples'),
('dare', 'spicy', 'Do a slow, dramatic hair flip.', 'couples'),
('dare', 'spicy', 'Send a cheeky wink emoji every other message.', 'couples'),
('dare', 'spicy', 'Act like you''re writing a heartfelt love letter.', 'couples'),
('dare', 'spicy', 'Send a flirty meme to the group.', 'couples'),
('dare', 'spicy', 'Describe a perfect date night outfit.', 'couples'),
('dare', 'spicy', 'Whisper "I''m yours" in the voice note.', 'couples'),
('dare', 'spicy', 'Draw a heart with your lips and share a photo.', 'couples'),
('dare', 'spicy', 'Pretend to serenade someone for one round.', 'couples'),
('dare', 'spicy', 'Share a spicy dare idea for someone else.', 'couples'),
('dare', 'spicy', 'Write a silly love song line.', 'couples'),
('dare', 'spicy', 'Do a dramatic sigh on video.', 'couples'),
('dare', 'spicy', 'Pretend to be swept off your feet.', 'couples'),
('dare', 'spicy', 'Act like you''re proposing to your phone.', 'couples');

-- ============================================
-- COUPLES MODE - SPICY TRUTHS (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('truth', 'spicy', 'What''s the most flirtatious thing you''ve done recently?', 'couples'),
('truth', 'spicy', 'What''s something you want to try but haven''t said yet?', 'couples'),
('truth', 'spicy', 'What''s the sexiest compliment you''ve received?', 'couples'),
('truth', 'spicy', 'Have you ever sent a flirty message to the wrong person?', 'couples'),
('truth', 'spicy', 'What''s your biggest turn-on in a partner?', 'couples'),
('truth', 'spicy', 'What''s the most romantic thing you want to try?', 'couples'),
('truth', 'spicy', 'Have you ever acted jealous to get attention?', 'couples'),
('truth', 'spicy', 'What''s your secret love language?', 'couples'),
('truth', 'spicy', 'Have you ever been tempted by someone else?', 'couples'),
('truth', 'spicy', 'What''s a fantasy you want to share?', 'couples'),
('truth', 'spicy', 'Have you ever had a crush on a friend''s partner?', 'couples'),
('truth', 'spicy', 'What''s your favorite thing to do after dark?', 'couples'),
('truth', 'spicy', 'Have you ever lied about how you feel in a relationship?', 'couples'),
('truth', 'spicy', 'What''s your wildest date idea?', 'couples'),
('truth', 'spicy', 'What''s the most seductive thing you''ve done?', 'couples'),
('truth', 'spicy', 'Have you ever faked being attracted to someone?', 'couples'),
('truth', 'spicy', 'What''s your favorite way to flirt?', 'couples'),
('truth', 'spicy', 'Have you ever been caught daydreaming about someone?', 'couples'),
('truth', 'spicy', 'What''s the most intimate thing you''ve seen in a partner?', 'couples'),
('truth', 'spicy', 'Have you ever given a secret gift or surprise?', 'couples'),
('truth', 'spicy', 'What''s your favorite physical touch?', 'couples'),
('truth', 'spicy', 'Have you ever sent a risky photo or message?', 'couples'),
('truth', 'spicy', 'What''s something you want your partner to do more?', 'couples'),
('truth', 'spicy', 'Have you ever been caught checking out someone else?', 'couples'),
('truth', 'spicy', 'What''s the most exciting place you''ve been intimate?', 'couples'),
('truth', 'spicy', 'Have you ever kept a secret from your partner?', 'couples'),
('truth', 'spicy', 'What''s something romantic you''re afraid to say out loud?', 'couples'),
('truth', 'spicy', 'Have you ever fantasized about someone else during intimacy?', 'couples'),
('truth', 'spicy', 'What''s your favorite thing about your partner''s personality?', 'couples'),
('truth', 'spicy', 'Have you ever wanted to spice up your love life?', 'couples'),
('truth', 'spicy', 'What''s the wildest fantasy you share with your partner?', 'couples'),
('truth', 'spicy', 'Have you ever been jealous of a friend''s partner?', 'couples'),
('truth', 'spicy', 'What''s a secret desire you''ve never shared?', 'couples'),
('truth', 'spicy', 'Have you ever flirted just for fun?', 'couples'),
('truth', 'spicy', 'What''s the most romantic thing you''ve planned?', 'couples'),
('truth', 'spicy', 'Have you ever kept a romantic secret?', 'couples'),
('truth', 'spicy', 'What''s your favorite way to tease your partner?', 'couples'),
('truth', 'spicy', 'Have you ever been caught making a romantic gesture?', 'couples'),
('truth', 'spicy', 'What''s a seductive move you love?', 'couples'),
('truth', 'spicy', 'Have you ever sent a love poem or message?', 'couples'),
('truth', 'spicy', 'What''s something daring you''ve done for love?', 'couples'),
('truth', 'spicy', 'Have you ever been tempted to flirt with someone else?', 'couples'),
('truth', 'spicy', 'What''s the naughtiest thing you''ve whispered during intimacy?', 'couples'),
('truth', 'spicy', 'Have you ever given or received a secret touch?', 'couples'),
('truth', 'spicy', 'What''s your favorite romantic memory together?', 'couples'),
('truth', 'spicy', 'Have you ever wanted to break the rules for love?', 'couples'),
('truth', 'spicy', 'What''s something you want to try in the bedroom?', 'couples'),
('truth', 'spicy', 'Have you ever fantasized about surprise dates?', 'couples'),
('truth', 'spicy', 'What''s the boldest romantic thing you''ve done?', 'couples'),
('truth', 'spicy', 'Have you ever wished for more romance?', 'couples'),
('truth', 'spicy', 'What''s a secret you keep about your love life?', 'couples'),
('truth', 'spicy', 'Have you ever planned a romantic getaway?', 'couples'),
('truth', 'spicy', 'What''s the most memorable kiss you''ve had?', 'couples'),
('truth', 'spicy', 'Have you ever flirted in front of your partner just to tease?', 'couples'),
('truth', 'spicy', 'What''s your favorite way to be loved?', 'couples'),
('truth', 'spicy', 'Have you ever been caught daydreaming about an ex?', 'couples'),
('truth', 'spicy', 'What''s a romantic fantasy you''d like to try?', 'couples');
