-- Part 3: Couples Mode - All Questions
-- Run this AFTER part2

-- ============================================
-- COUPLES MODE - MILD DARES (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('dare', 'mild', 'Share your favorite romantic movie line.', 'couples'),
('dare', 'mild', 'Send a cute selfie with a heart gesture.', 'couples'),
('dare', 'mild', 'Whisper a secret to the camera.', 'couples'),
('dare', 'mild', 'Write a sweet message in chat for your partner.', 'couples'),
('dare', 'mild', 'Draw a heart and share a photo.', 'couples'),
('dare', 'mild', 'Do a slow dance with a pretend partner.', 'couples'),
('dare', 'mild', 'Send a voice message saying "You''re amazing."', 'couples'),
('dare', 'mild', 'Describe your ideal date in 3 sentences.', 'couples'),
('dare', 'mild', 'Share your favorite flower and why.', 'couples'),
('dare', 'mild', 'Pretend to serenade your partner.', 'couples'),
('dare', 'mild', 'Send a photo of your hand making a heart.', 'couples'),
('dare', 'mild', 'List 3 things you love about your partner.', 'couples'),
('dare', 'mild', 'Send a selfie with a cupid arrow drawn (digital or physical).', 'couples'),
('dare', 'mild', 'Say "I love you" in a funny accent.', 'couples'),
('dare', 'mild', 'Write a love haiku and share.', 'couples'),
('dare', 'mild', 'Act shy as if on a first date.', 'couples'),
('dare', 'mild', 'Whisper your partner''s name dramatically.', 'couples'),
('dare', 'mild', 'Share your best kissing face (photo).', 'couples'),
('dare', 'mild', 'Compliment your partner''s smile.', 'couples'),
('dare', 'mild', 'Describe your favorite thing to do together.', 'couples'),
('dare', 'mild', 'Tell a flirty joke.', 'couples'),
('dare', 'mild', 'Draw a kiss mark and share.', 'couples'),
('dare', 'mild', 'Pretend to propose marriage.', 'couples'),
('dare', 'mild', 'Share your favorite romantic song and sing a line.', 'couples'),
('dare', 'mild', 'Give a virtual wink.', 'couples'),
('dare', 'mild', 'Send a message with hearts and kisses emojis.', 'couples'),
('dare', 'mild', 'Make a cute nickname for your partner.', 'couples'),
('dare', 'mild', 'Act like you''re meeting your crush for the first time.', 'couples'),
('dare', 'mild', 'Share your favorite love quote.', 'couples'),
('dare', 'mild', 'Describe your partner using only three words.', 'couples'),
('dare', 'mild', 'Send a selfie blowing a kiss.', 'couples'),
('dare', 'mild', 'Tell about your first crush ever.', 'couples'),
('dare', 'mild', 'Share the sweetest text you''ve ever received.', 'couples'),
('dare', 'mild', 'Pretend you''re on a romantic beach.', 'couples'),
('dare', 'mild', 'Sing a love song for 10 seconds.', 'couples'),
('dare', 'mild', 'Describe your dream date night.', 'couples'),
('dare', 'mild', 'Share your favorite romantic memory.', 'couples'),
('dare', 'mild', 'Write a love letter opening line.', 'couples'),
('dare', 'mild', 'Share how you felt on your first date.', 'couples'),
('dare', 'mild', 'Act like you''re slow dancing.', 'couples'),
('dare', 'mild', 'Say your partner''s name with a loving tone.', 'couples'),
('dare', 'mild', 'Share your best puppy eyes photo.', 'couples'),
('dare', 'mild', 'Describe your partner''s cutest habit.', 'couples'),
('dare', 'mild', 'Say what you find most attractive about your partner.', 'couples'),
('dare', 'mild', 'Send a selfie with a flower behind your ear.', 'couples'),
('dare', 'mild', 'Write a flirty sentence using only emojis.', 'couples'),
('dare', 'mild', 'Compliment your partner''s sense of humor.', 'couples'),
('dare', 'mild', 'Send your favorite romantic movie scene clip or description.', 'couples'),
('dare', 'mild', 'Pretend you''re giving your partner a massage.', 'couples'),
('dare', 'mild', 'Whisper your partner''s favorite pet name.', 'couples'),
('dare', 'mild', 'Share a silly romantic nickname.', 'couples'),
('dare', 'mild', 'Describe what you like most about your partner''s laugh.', 'couples'),
('dare', 'mild', 'Send a message staring into imaginary eyes.', 'couples'),
('dare', 'mild', 'Pretend texting your crush in slow motion.', 'couples'),
('dare', 'mild', 'Make up a cute dance and share a video.', 'couples'),
('dare', 'mild', 'Say "You''re my favorite" three times dramatically.', 'couples'),
('dare', 'mild', 'Send a picture of your smile right now.', 'couples'),
('dare', 'mild', 'Share your favorite romantic emoji combo.', 'couples'),
('dare', 'mild', 'Act romantic in chat for 2 minutes.', 'couples'),
('dare', 'mild', 'Describe how you''d surprise your partner on a date.', 'couples'),
('dare', 'mild', 'Write a cute poem about love.', 'couples');
