-- Part 4: Couples Mode Truths
-- Run this AFTER part3

-- ============================================
-- COUPLES MODE - MILD TRUTHS (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('truth', 'mild', 'What was your first impression of your partner?', 'couples'),
('truth', 'mild', 'What''s your favorite thing about your partner?', 'couples'),
('truth', 'mild', 'When was your first crush and who was it?', 'couples'),
('truth', 'mild', 'What''s your idea of a perfect date?', 'couples'),
('truth', 'mild', 'How do you like to be comforted when you''re sad?', 'couples'),
('truth', 'mild', 'What''s your favorite romantic movie or song?', 'couples'),
('truth', 'mild', 'What was your most memorable date?', 'couples'),
('truth', 'mild', 'What''s something you want to try together?', 'couples'),
('truth', 'mild', 'How did you know you liked your partner?', 'couples'),
('truth', 'mild', 'What''s your favorite physical feature of your partner?', 'couples'),
('truth', 'mild', 'What''s your favorite memory with your partner?', 'couples'),
('truth', 'mild', 'What''s your love language (how you show/receive love)?', 'couples'),
('truth', 'mild', 'What''s the sweetest thing someone has done for you?', 'couples'),
('truth', 'mild', 'How do you express affection?', 'couples'),
('truth', 'mild', 'What''s a little thing that makes you happy?', 'couples'),
('truth', 'mild', 'What''s your ideal way to spend time together?', 'couples'),
('truth', 'mild', 'Have you ever been in love before?', 'couples'),
('truth', 'mild', 'Do you believe in soulmates?', 'couples'),
('truth', 'mild', 'What''s the most romantic thing you''ve ever done?', 'couples'),
('truth', 'mild', 'How do you feel about public displays of affection?', 'couples'),
('truth', 'mild', 'What''s the nicest compliment you''ve received?', 'couples'),
('truth', 'mild', 'What''s your favorite love song or poem?', 'couples'),
('truth', 'mild', 'What''s your favorite way to say "I love you"?', 'couples'),
('truth', 'mild', 'Do you prefer big gestures or small surprises?', 'couples'),
('truth', 'mild', 'What''s something you admire about your partner?', 'couples'),
('truth', 'mild', 'How do you handle disagreements?', 'couples'),
('truth', 'mild', 'What''s a romantic place you want to visit?', 'couples'),
('truth', 'mild', 'What''s the cutest thing your partner has done?', 'couples'),
('truth', 'mild', 'What do you think is key to a good relationship?', 'couples'),
('truth', 'mild', 'What''s your favorite way to celebrate special occasions?', 'couples'),
('truth', 'mild', 'Have you ever written a love letter or note?', 'couples'),
('truth', 'mild', 'What''s your most memorable kiss?', 'couples'),
('truth', 'mild', 'What''s a dream for your future together?', 'couples'),
('truth', 'mild', 'What''s your favorite way to spend a lazy day with your partner?', 'couples'),
('truth', 'mild', 'Have you ever felt butterflies around your partner?', 'couples'),
('truth', 'mild', 'What''s the best gift you ever gave or received?', 'couples'),
('truth', 'mild', 'What''s the quirkiest habit your partner has?', 'couples'),
('truth', 'mild', 'How would you describe your partner in three words?', 'couples'),
('truth', 'mild', 'What''s the most thoughtful thing your partner has done for you?', 'couples'),
('truth', 'mild', 'What scares you the most about relationships?', 'couples'),
('truth', 'mild', 'What''s the best advice about love you''ve ever heard?', 'couples'),
('truth', 'mild', 'What''s something your partner does that always makes you smile?', 'couples'),
('truth', 'mild', 'What''s your idea of a romantic weekend?', 'couples'),
('truth', 'mild', 'Have you ever surprised your partner? How?', 'couples'),
('truth', 'mild', 'What''s your favorite way to show affection without words?', 'couples'),
('truth', 'mild', 'How do you like to be comforted after a bad day?', 'couples'),
('truth', 'mild', 'How do you celebrate anniversaries?', 'couples'),
('truth', 'mild', 'What''s your favorite memory of a vacation together?', 'couples'),
('truth', 'mild', 'What''s a funny habit you have together?', 'couples'),
('truth', 'mild', 'Have you ever wrote a song or poem for your partner?', 'couples'),
('truth', 'mild', 'What''s your favorite thing to do on a date night?', 'couples'),
('truth', 'mild', 'What''s your secret to making your partner smile?', 'couples'),
('truth', 'mild', 'How do you feel about love at first sight?', 'couples'),
('truth', 'mild', 'What''s your favorite love-related quote or saying?', 'couples'),
('truth', 'mild', 'How do you support each other in tough times?', 'couples'),
('truth', 'mild', 'How did you know the moment you fell for your partner?', 'couples'),
('truth', 'mild', 'What''s your favorite way to say goodnight?', 'couples'),
('truth', 'mild', 'What''s a challenge you''ve overcome together?', 'couples'),
('truth', 'mild', 'What''s your favorite romantic gesture you''ve made?', 'couples');
