-- Part 6: Couples Mode - Extreme Questions
-- Run this to add Couples Extreme Dares and Truths

-- ============================================
-- COUPLES MODE - EXTREME DARES (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('dare', 'extreme', 'Send your wildest selfie (with consent).', 'couples'),
('dare', 'extreme', 'Serenade someone in the group.', 'couples'),
('dare', 'extreme', 'Text your crush a flirty "hey."', 'couples'),
('dare', 'extreme', 'Share something you wouldn''t admit IRL.', 'couples'),
('dare', 'extreme', 'Share your most awkward romantic photo.', 'couples'),
('dare', 'extreme', 'Send a voice note confessing a secret crush.', 'couples'),
('dare', 'extreme', 'Reenact a steamy movie scene on video.', 'couples'),
('dare', 'extreme', 'Pretend to have a crush on someone in the group.', 'couples'),
('dare', 'extreme', 'Send a dramatic love confession.', 'couples'),
('dare', 'extreme', 'Do a playful striptease (keep it safe and tasteful).', 'couples'),
('dare', 'extreme', 'Share a daring fantasy.', 'couples'),
('dare', 'extreme', 'Text your last ex something funny.', 'couples'),
('dare', 'extreme', 'Draw a kiss mark on your hand and show it.', 'couples'),
('dare', 'extreme', 'Share your most embarrassing text message.', 'couples'),
('dare', 'extreme', 'Write a raunchy limerick.', 'couples'),
('dare', 'extreme', 'Give a virtual "lap dance" on camera.', 'couples'),
('dare', 'extreme', 'Send a bold flirty message to a stranger.', 'couples'),
('dare', 'extreme', 'Do your best seductive dance.', 'couples'),
('dare', 'extreme', 'Send a sultry selfie (always optional).', 'couples'),
('dare', 'extreme', 'Make a video pretending to blush.', 'couples'),
('dare', 'extreme', 'Read a naughty text in a dramatic voice.', 'couples'),
('dare', 'extreme', 'Act like you just got caught flirting.', 'couples'),
('dare', 'extreme', 'Share your "hidden" love song playlist.', 'couples'),
('dare', 'extreme', 'Pretend to be your crush on video.', 'couples'),
('dare', 'extreme', 'Write a steamy text, share redacted version.', 'couples'),
('dare', 'extreme', 'Send a picture of your wildest hair day.', 'couples'),
('dare', 'extreme', 'Make an over-the-top romantic speech.', 'couples'),
('dare', 'extreme', 'Share an intimate secret (optional).', 'couples'),
('dare', 'extreme', 'Recite a raunchy poem.', 'couples'),
('dare', 'extreme', 'Do 5 sexy poses and share best one.', 'couples'),
('dare', 'extreme', 'Make a flirty pickup line video.', 'couples'),
('dare', 'extreme', 'Record a moan (funny or real).', 'couples'),
('dare', 'extreme', 'Tell about your weirdest crush.', 'couples'),
('dare', 'extreme', 'Send a "goodnight" kiss video.', 'couples'),
('dare', 'extreme', 'Do a dramatic hair toss.', 'couples'),
('dare', 'extreme', 'Share a photo of your wildest outfit.', 'couples'),
('dare', 'extreme', 'Whisper your best flirt move.', 'couples'),
('dare', 'extreme', 'Act out a flirt fight scene.', 'couples'),
('dare', 'extreme', 'Share something you regret saying to a crush.', 'couples'),
('dare', 'extreme', 'Send a daring selfie with filters.', 'couples'),
('dare', 'extreme', 'Share the last thing you searched in private.', 'couples'),
('dare', 'extreme', 'Pretend you''re writing a hot text.', 'couples'),
('dare', 'extreme', 'Send a video of blowing a kiss.', 'couples'),
('dare', 'extreme', 'Tell a story involving an awkward date.', 'couples'),
('dare', 'extreme', 'Share your "cringe" romantic moment.', 'couples'),
('dare', 'extreme', 'Give a sultry stare into the camera.', 'couples'),
('dare', 'extreme', 'Share your favorite romantic emoji streak.', 'couples'),
('dare', 'extreme', 'Act like a lovesick puppy.', 'couples'),
('dare', 'extreme', 'Send a photo of your best pout.', 'couples'),
('dare', 'extreme', 'Pretend to be shy and embarrassed.', 'couples'),
('dare', 'extreme', 'Do a dramatic love sigh.', 'couples'),
('dare', 'extreme', 'Tell the group about your worst love advice.', 'couples'),
('dare', 'extreme', 'Share an awkward hug story.', 'couples'),
('dare', 'extreme', 'Write a flirty chat line.', 'couples'),
('dare', 'extreme', 'Send a romantic quote you like.', 'couples'),
('dare', 'extreme', 'Whisper "I''m yours" dramatically.', 'couples'),
('dare', 'extreme', 'Make a funny romantic pun.', 'couples'),
('dare', 'extreme', 'Act out a smitten crush.', 'couples'),
('dare', 'extreme', 'Pretend you''re lost in someone''s eyes.', 'couples'),
('dare', 'extreme', 'Share a wild romantic daydream.', 'couples');

-- ============================================
-- COUPLES MODE - EXTREME TRUTHS (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('truth', 'extreme', 'What''s the most intimate secret you''ve never told your partner?', 'couples'),
('truth', 'extreme', 'Have you ever fantasized about someone else while with your partner?', 'couples'),
('truth', 'extreme', 'What''s your wildest sexual fantasy?', 'couples'),
('truth', 'extreme', 'Have you ever lied about your feelings in a relationship?', 'couples'),
('truth', 'extreme', 'What''s the most scandalous place you''ve made love?', 'couples'),
('truth', 'extreme', 'Have you ever sent explicit photos to your partner or someone else?', 'couples'),
('truth', 'extreme', 'What''s a secret kink or desire you''re afraid to admit?', 'couples'),
('truth', 'extreme', 'Have you ever fantasized about someone here while being with your partner?', 'couples'),
('truth', 'extreme', 'What''s the most daring thing you''ve done for love or sex?', 'couples'),
('truth', 'extreme', 'Have you ever cheated emotionally or physically?', 'couples'),
('truth', 'extreme', 'What''s your biggest regret in love or intimacy?', 'couples'),
('truth', 'extreme', 'Have you ever wanted to try something taboo?', 'couples'),
('truth', 'extreme', 'What''s the most intense intimate moment you remember?', 'couples'),
('truth', 'extreme', 'Have you ever hidden your true feelings about a relationship?', 'couples'),
('truth', 'extreme', 'What''s something you want to confess but haven''t?', 'couples'),
('truth', 'extreme', 'Have you ever been in love with someone you couldn''t have?', 'couples'),
('truth', 'extreme', 'What''s your secret desire you''re too shy to share?', 'couples'),
('truth', 'extreme', 'Have you ever been unfaithful in thought or action?', 'couples'),
('truth', 'extreme', 'What''s the wildest intimate dare you''d accept?', 'couples'),
('truth', 'extreme', 'Have you ever used a sex toy or accessory?', 'couples'),
('truth', 'extreme', 'What''s a fantasy involving someone here you''d try if safe?', 'couples'),
('truth', 'extreme', 'Have you ever had a secret affair or crush?', 'couples'),
('truth', 'extreme', 'What''s the most vulnerable you''ve ever felt in love?', 'couples'),
('truth', 'extreme', 'Have you ever lied about your sexual history?', 'couples'),
('truth', 'extreme', 'What''s the most passionate thing you''ve experienced?', 'couples'),
('truth', 'extreme', 'Have you ever regretted something you did for love?', 'couples'),
('truth', 'extreme', 'What''s the craziest intimate experience you''ve ever had?', 'couples'),
('truth', 'extreme', 'Have you ever been afraid to tell your partner something?', 'couples'),
('truth', 'extreme', 'What''s a love secret you keep hidden?', 'couples'),
('truth', 'extreme', 'Have you ever experienced unrequited love?', 'couples'),
('truth', 'extreme', 'What''s your most intense or wildest dream about love or sex?', 'couples'),
('truth', 'extreme', 'Have you ever had a secret crush on someone''s partner?', 'couples'),
('truth', 'extreme', 'What''s the boldest thing you''ve admitted here?', 'couples'),
('truth', 'extreme', 'Have you ever imagined a forbidden romance?', 'couples'),
('truth', 'extreme', 'What''s something intimate you want to try but too shy to ask?', 'couples'),
('truth', 'extreme', 'Have you ever hidden a secret lover?', 'couples'),
('truth', 'extreme', 'What''s the most risque confession you''ve made?', 'couples'),
('truth', 'extreme', 'Have you ever done something wild behind your partner''s back?', 'couples'),
('truth', 'extreme', 'What''s the most romantic or sexy lie you''ve told?', 'couples'),
('truth', 'extreme', 'Have you ever wished you could turn back time in a relationship?', 'couples'),
('truth', 'extreme', 'What''s your most taboo fantasy?', 'couples'),
('truth', 'extreme', 'Have you ever felt jealous of your partner''s friend?', 'couples'),
('truth', 'extreme', 'What''s the most explicit text you''ve sent or received?', 'couples'),
('truth', 'extreme', 'Have you ever fantasized about an ex while with your partner?', 'couples'),
('truth', 'extreme', 'What''s your biggest fear about love and trust?', 'couples'),
('truth', 'extreme', 'Have you ever kept your relationship status secret?', 'couples'),
('truth', 'extreme', 'What''s a wild love story no one knows about?', 'couples'),
('truth', 'extreme', 'Have you ever been caught doing something naughty?', 'couples'),
('truth', 'extreme', 'What''s your favorite intimate memory you rarely share?', 'couples'),
('truth', 'extreme', 'Have you ever faked interest in something your partner liked?', 'couples'),
('truth', 'extreme', 'What''s your secret desire for your love life?', 'couples'),
('truth', 'extreme', 'Have you ever regretted breaking up with someone?', 'couples'),
('truth', 'extreme', 'What''s something intimate you want to explore more?', 'couples'),
('truth', 'extreme', 'Have you ever kept a secret crush from your partner?', 'couples'),
('truth', 'extreme', 'What''s the darkest secret of your love life?', 'couples'),
('truth', 'extreme', 'Have you ever experienced forbidden love or desire?', 'couples'),
('truth', 'extreme', 'What''s a fantasy you''ve never shared with anyone?', 'couples');
