-- Complete replacement of Truth or Dare questions
-- Run this in Supabase SQL Editor

-- First, delete all existing questions
DELETE FROM truth_or_dare_questions;

-- Ensure the table has the correct structure
ALTER TABLE truth_or_dare_questions 
ADD COLUMN IF NOT EXISTS mode TEXT DEFAULT 'friends' CHECK (mode IN ('friends', 'couples'));

ALTER TABLE truth_or_dare_questions DROP COLUMN IF EXISTS points;

-- ============================================
-- FRIENDS MODE - MILD DARES (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('dare', 'mild', 'Do 10 jumping jacks and take a selfie.', 'friends'),
('dare', 'mild', 'Send the last photo in your camera roll.', 'friends'),
('dare', 'mild', 'Write your name backward in chat.', 'friends'),
('dare', 'mild', 'Share your goofiest face in chat.', 'friends'),
('dare', 'mild', 'Sing a part of your favorite song.', 'friends'),
('dare', 'mild', 'Send a voice note of your best laugh.', 'friends'),
('dare', 'mild', 'Balance a book on your head for 30 seconds.', 'friends'),
('dare', 'mild', 'Draw a silly face and share a pic.', 'friends'),
('dare', 'mild', 'Type a message only using emojis.', 'friends'),
('dare', 'mild', 'Mime your favorite animal for 15 seconds on video.', 'friends'),
('dare', 'mild', 'Say the alphabet backward.', 'friends'),
('dare', 'mild', 'Do a quick dance on camera.', 'friends'),
('dare', 'mild', 'Write a funny poem about the group.', 'friends'),
('dare', 'mild', 'Share a childhood nickname.', 'friends'),
('dare', 'mild', 'Post a funny meme from your phone.', 'friends'),
('dare', 'mild', 'Imitate your favorite cartoon character.', 'friends'),
('dare', 'mild', 'Do your best impression of another player.', 'friends'),
('dare', 'mild', 'Show your weirdest dance move.', 'friends'),
('dare', 'mild', 'Do 5 push-ups and share proof.', 'friends'),
('dare', 'mild', 'Speak like a pirate for the next 3 messages.', 'friends'),
('dare', 'mild', 'Draw a mustache on your face and show.', 'friends'),
('dare', 'mild', 'Wear a silly hat and keep it for 2 rounds.', 'friends'),
('dare', 'mild', 'Share your favorite emoji and why.', 'friends'),
('dare', 'mild', 'Send a message in a different language.', 'friends'),
('dare', 'mild', 'Act like a robot until your next turn.', 'friends'),
('dare', 'mild', 'Share your phone''s current wallpaper.', 'friends'),
('dare', 'mild', 'Take a selfie with a big smile.', 'friends'),
('dare', 'mild', 'Try to balance a spoon on your nose.', 'friends'),
('dare', 'mild', 'Say a tongue twister three times fast.', 'friends'),
('dare', 'mild', 'Do 10 squats and show it on video.', 'friends'),
('dare', 'mild', 'Make a silly rhyme about the last player who spoke.', 'friends'),
('dare', 'mild', 'Post an edited photo of yourself with a filter.', 'friends'),
('dare', 'mild', 'Share your weirdest selfie.', 'friends'),
('dare', 'mild', 'Use only GIFs to answer next 2 questions.', 'friends'),
('dare', 'mild', 'Draw an animal with your non-dominant hand.', 'friends'),
('dare', 'mild', 'Find and share a random object nearby.', 'friends'),
('dare', 'mild', 'Act like your favorite superhero for 20 seconds.', 'friends'),
('dare', 'mild', 'Say your favorite joke with enthusiasm.', 'friends'),
('dare', 'mild', 'Send your best funny face.', 'friends'),
('dare', 'mild', 'Talk like a celebrity for one round.', 'friends'),
('dare', 'mild', 'Send a voice note singing happy birthday.', 'friends'),
('dare', 'mild', 'Pretend to be a news anchor, report something silly.', 'friends'),
('dare', 'mild', 'Say compliment to every player in chat.', 'friends'),
('dare', 'mild', 'Show your best "surprised" face.', 'friends'),
('dare', 'mild', 'Pretend to be your pet or animal.', 'friends'),
('dare', 'mild', 'Share the silliest thing you own.', 'friends'),
('dare', 'mild', 'Share a funny ringtone or notification sound.', 'friends'),
('dare', 'mild', 'Draw a heart with your finger on screen.', 'friends'),
('dare', 'mild', 'Say the days of the week backward.', 'friends'),
('dare', 'mild', 'Do your best scary face (video or photo).', 'friends'),
('dare', 'mild', 'Share your favorite dance move.', 'friends'),
('dare', 'mild', 'Write a silly sentence with your toes (photo).', 'friends'),
('dare', 'mild', 'Post your favorite cartoon theme song lyrics.', 'friends'),
('dare', 'mild', 'Share what you''d do if you were invisible.', 'friends'),
('dare', 'mild', 'Pretend to be a chef describing your favorite dish.', 'friends'),
('dare', 'mild', 'Make up a story about why you''re late today.', 'friends'),
('dare', 'mild', 'Spell your name using objects nearby.', 'friends'),
('dare', 'mild', 'Send a voice note laughing uncontrollably.', 'friends'),
('dare', 'mild', 'Make up a funny nickname for one player.', 'friends'),
('dare', 'mild', 'Act like you''re stuck in slow motion for next message.', 'friends'),
('dare', 'mild', 'Share your weirdest habit.', 'friends'),
('dare', 'mild', 'Say "I love pizza" in three different accents.', 'friends'),
('dare', 'mild', 'Do a playful roar and share a video.', 'friends'),
('dare', 'mild', 'Show your funny dance with a broom or stick.', 'friends'),
('dare', 'mild', 'Invent a game on the spot and teach it.', 'friends'),
('dare', 'mild', 'Send a silly selfie with exaggerated eyebrows.', 'friends');

-- ============================================
-- FRIENDS MODE - MILD TRUTHS (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('truth', 'mild', 'What''s your most embarrassing childhood memory?', 'friends'),
('truth', 'mild', 'Have you ever told a lie to get out of trouble?', 'friends'),
('truth', 'mild', 'What''s the weirdest thing you believed as a kid?', 'friends'),
('truth', 'mild', 'Who was your first crush?', 'friends'),
('truth', 'mild', 'Have you ever stared at yourself in the mirror for a long time?', 'friends'),
('truth', 'mild', 'What''s your favorite snack that no one else likes?', 'friends'),
('truth', 'mild', 'Have you ever been caught doing something you shouldn''t?', 'friends'),
('truth', 'mild', 'What''s a secret talent you have?', 'friends'),
('truth', 'mild', 'What''s the silliest thing you''re afraid of?', 'friends'),
('truth', 'mild', 'Have you ever pretended to be sick to skip school/work?', 'friends'),
('truth', 'mild', 'What''s the worst haircut you ever had?', 'friends'),
('truth', 'mild', 'Have you ever talked to yourself out loud?', 'friends'),
('truth', 'mild', 'Do you still sleep with a stuffed animal or blanket?', 'friends'),
('truth', 'mild', 'What''s your guilty pleasure TV show or movie?', 'friends'),
('truth', 'mild', 'Have you ever been caught singing in the shower?', 'friends'),
('truth', 'mild', 'What''s your weirdest habit?', 'friends'),
('truth', 'mild', 'Have you ever sent a message to the wrong person?', 'friends'),
('truth', 'mild', 'What''s the funniest thing you''ve ever done on a dare?', 'friends'),
('truth', 'mild', 'Have you ever kept a secret for a friend?', 'friends'),
('truth', 'mild', 'What''s the weirdest nickname you''ve ever had?', 'friends'),
('truth', 'mild', 'Have you ever played a prank on someone?', 'friends'),
('truth', 'mild', 'What''s the most childish thing you still do?', 'friends'),
('truth', 'mild', 'Have you ever laughed so hard you cried?', 'friends'),
('truth', 'mild', 'What''s a weird food combination you actually like?', 'friends'),
('truth', 'mild', 'Have you ever fallen asleep in class or a meeting?', 'friends'),
('truth', 'mild', 'What''s your favorite joke or meme?', 'friends'),
('truth', 'mild', 'Have you ever broken something and not told anyone?', 'friends'),
('truth', 'mild', 'Have you ever gotten lost somewhere?', 'friends'),
('truth', 'mild', 'What''s the worst gift you''ve ever received?', 'friends'),
('truth', 'mild', 'What''s one thing you wish people knew about you?', 'friends'),
('truth', 'mild', 'Have you ever won an award or competition?', 'friends'),
('truth', 'mild', 'What''s your weirdest phone wallpaper or ringtone?', 'friends'),
('truth', 'mild', 'Have you ever stalked someone on social media?', 'friends'),
('truth', 'mild', 'What''s your favorite way to relax?', 'friends'),
('truth', 'mild', 'Have you ever accidentally sent a text you regretted?', 'friends'),
('truth', 'mild', 'What''s the last thing you searched on your phone?', 'friends'),
('truth', 'mild', 'Who in this group would you call in an emergency?', 'friends'),
('truth', 'mild', 'Have you ever sung karaoke? What song?', 'friends'),
('truth', 'mild', 'What''s your favorite memory with friends?', 'friends'),
('truth', 'mild', 'Have you ever cried during a movie?', 'friends'),
('truth', 'mild', 'What''s your weirdest internet addiction or habit?', 'friends'),
('truth', 'mild', 'Have you ever stayed up all night? Why?', 'friends'),
('truth', 'mild', 'What''s a secret you''ve never told anyone?', 'friends'),
('truth', 'mild', 'What''s your favorite thing about yourself?', 'friends'),
('truth', 'mild', 'Have you ever made a new friend online?', 'friends'),
('truth', 'mild', 'What''s something you want to learn but haven''t yet?', 'friends'),
('truth', 'mild', 'Have you ever forgotten a friend''s birthday?', 'friends'),
('truth', 'mild', 'What''s your most embarrassing fashion moment?', 'friends'),
('truth', 'mild', 'Have you ever faked being busy to avoid someone?', 'friends'),
('truth', 'mild', 'What''s the weirdest gift you''ve ever given?', 'friends'),
('truth', 'mild', 'What''s your biggest fear?', 'friends'),
('truth', 'mild', 'Have you ever given or received a surprise party?', 'friends'),
('truth', 'mild', 'What''s the most ridiculous outfit you''ve worn?', 'friends'),
('truth', 'mild', 'Who''s your favorite comedian or funny person?', 'friends'),
('truth', 'mild', 'Have you ever snuck out or done something rebellious?', 'friends'),
('truth', 'mild', 'What''s your go-to comfort food?', 'friends'),
('truth', 'mild', 'What''s a movie or show that made you cry?', 'friends'),
('truth', 'mild', 'Have you ever had a crush on a celebrity?', 'friends'),
('truth', 'mild', 'What''s something you''re really proud of?', 'friends'),
('truth', 'mild', 'What''s a bad habit you''re trying to break?', 'friends'),
('truth', 'mild', 'What''s your dream vacation spot?', 'friends'),
('truth', 'mild', 'Have you ever lied on your resume or application?', 'friends');

-- Continue with remaining questions in next message due to length...

-- ============================================
-- FRIENDS MODE - SPICY DARES (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('dare', 'spicy', 'Send a flirty message to the last person you DM''ed.', 'friends'),
('dare', 'spicy', 'Compliment someone flirtatiously in chat.', 'friends'),
('dare', 'spicy', 'Post a "cringe" status update.', 'friends'),
('dare', 'spicy', 'Share a funny pick-up line on social media.', 'friends'),
('dare', 'spicy', 'Whisper a secret fantasy in chat.', 'friends'),
('dare', 'spicy', 'Send a GIF that best describes your love life.', 'friends'),
('dare', 'spicy', 'Record a cheeky voice note.', 'friends'),
('dare', 'spicy', 'Share a selfie with your wildest hair.', 'friends'),
('dare', 'spicy', 'Pretend to be a famous lover for a round.', 'friends'),
('dare', 'spicy', 'Reenact a movie kiss scene.', 'friends'),
('dare', 'spicy', 'Change your profile pic to a funny romantic one for 24h.', 'friends'),
('dare', 'spicy', 'Send a voice note acting shy.', 'friends'),
('dare', 'spicy', 'Tell a spicy joke.', 'friends'),
('dare', 'spicy', 'Text "I can''t stop thinking about you" to a friend (screen off).', 'friends'),
('dare', 'spicy', 'Make a mock dramatic love confession.', 'friends'),
('dare', 'spicy', 'Share a screenshot of your chat crush (if comfortable).', 'friends'),
('dare', 'spicy', 'Do a flirty dance on camera.', 'friends'),
('dare', 'spicy', 'Act out a romantic movie breakup scene.', 'friends'),
('dare', 'spicy', 'Send a selfie biting your lip.', 'friends'),
('dare', 'spicy', 'Write a flirty tongue twister.', 'friends'),
('dare', 'spicy', 'Sing a love song badly on video.', 'friends'),
('dare', 'spicy', 'Name your favorite body part on a partner.', 'friends'),
('dare', 'spicy', 'Pretend to propose via chat.', 'friends'),
('dare', 'spicy', 'Share your weirdest date story.', 'friends'),
('dare', 'spicy', 'Do a playful seductive wink.', 'friends'),
('dare', 'spicy', 'Tell a romantic lie.', 'friends'),
('dare', 'spicy', 'Write a poem about a crush.', 'friends'),
('dare', 'spicy', 'Send a voice note blowing a kiss.', 'friends'),
('dare', 'spicy', 'Say a naughty phrase in a funny voice.', 'friends'),
('dare', 'spicy', 'Share your dream romantic getaway.', 'friends'),
('dare', 'spicy', 'Act like a cat flirting.', 'friends'),
('dare', 'spicy', 'Share your best "I''m interested" look photo.', 'friends'),
('dare', 'spicy', 'Write a text as if you''re seducing someone.', 'friends'),
('dare', 'spicy', 'Do 10 sexy stretches.', 'friends'),
('dare', 'spicy', 'Send a photo with lip gloss or kiss mark.', 'friends'),
('dare', 'spicy', 'Speak in a flirty language (real or made-up).', 'friends'),
('dare', 'spicy', 'Send a cute emoji combo to someone.', 'friends'),
('dare', 'spicy', 'Pretend you''re on a date in Paris.', 'friends'),
('dare', 'spicy', 'Make seductive sound effects.', 'friends'),
('dare', 'spicy', 'Name 3 ways you''d impress someone.', 'friends'),
('dare', 'spicy', 'Share your crush''s name with emojis only.', 'friends'),
('dare', 'spicy', 'Write a "Dear Diary" flirty entry.', 'friends'),
('dare', 'spicy', 'Recite a love poem from memory (or make one up).', 'friends'),
('dare', 'spicy', 'Send a selfie pretending to swoon.', 'friends'),
('dare', 'spicy', 'Compliment a player''s smile in a flirty way.', 'friends'),
('dare', 'spicy', 'Share your favorite romantic app or game.', 'friends'),
('dare', 'spicy', 'Do a slow, dramatic hair flip.', 'friends'),
('dare', 'spicy', 'Send a cheeky wink emoji every other message.', 'friends'),
('dare', 'spicy', 'Act like you''re writing a heartfelt love letter.', 'friends'),
('dare', 'spicy', 'Send a flirty meme to the group.', 'friends'),
('dare', 'spicy', 'Describe a perfect date night outfit.', 'friends'),
('dare', 'spicy', 'Whisper "I''m yours" in the voice note.', 'friends'),
('dare', 'spicy', 'Draw a heart with your lips and share a photo.', 'friends'),
('dare', 'spicy', 'Pretend to serenade someone for one round.', 'friends'),
('dare', 'spicy', 'Share a spicy dare idea for someone else.', 'friends'),
('dare', 'spicy', 'Write a silly love song line.', 'friends'),
('dare', 'spicy', 'Do a dramatic sigh on video.', 'friends'),
('dare', 'spicy', 'Pretend to be swept off your feet.', 'friends'),
('dare', 'spicy', 'Act like you''re proposing to your phone.', 'friends');

-- ============================================
-- FRIENDS MODE - SPICY TRUTHS (60+)
-- ============================================
INSERT INTO truth_or_dare_questions (type, spice_level, content, mode) VALUES
('truth', 'spicy', 'What''s the wildest rumor you''ve ever been part of?', 'friends'),
('truth', 'spicy', 'What''s a secret you''ve never told your family?', 'friends'),
('truth', 'spicy', 'Have you ever flirted with someone just for fun?', 'friends'),
('truth', 'spicy', 'What''s your most embarrassing crush story?', 'friends'),
('truth', 'spicy', 'Have you ever snuck out or done something rebellious?', 'friends'),
('truth', 'spicy', 'Have you ever been caught sneaking snacks?', 'friends'),
('truth', 'spicy', 'What''s the most awkward text message you''ve sent?', 'friends'),
('truth', 'spicy', 'Have you ever lied about your age?', 'friends'),
('truth', 'spicy', 'What''s your biggest insecurity?', 'friends'),
('truth', 'spicy', 'Have you ever cheated at a game or exam?', 'friends'),
('truth', 'spicy', 'What''s the craziest dare you''ve ever completed?', 'friends'),
('truth', 'spicy', 'Have you ever been rejected after confessing?', 'friends'),
('truth', 'spicy', 'What''s a weird habit you wish you could hide?', 'friends'),
('truth', 'spicy', 'Have you ever stalked someone on social media?', 'friends'),
('truth', 'spicy', 'Have you ever been in a physical fight?', 'friends'),
('truth', 'spicy', 'What''s the riskiest thing you''ve done while drunk?', 'friends'),
('truth', 'spicy', 'Have you ever been caught lying by a friend?', 'friends'),
('truth', 'spicy', 'What''s the weirdest thing you''ve searched online?', 'friends'),
('truth', 'spicy', 'Have you ever accidentally sent a message to the wrong person?', 'friends'),
('truth', 'spicy', 'What''s a secret you''re keeping from your best friend?', 'friends'),
('truth', 'spicy', 'Have you ever broken something and lied about it?', 'friends'),
('truth', 'spicy', 'What''s the craziest party you''ve been to?', 'friends'),
('truth', 'spicy', 'Have you ever been caught cheating on a test?', 'friends'),
('truth', 'spicy', 'What''s your wildest dream or fantasy?', 'friends'),
('truth', 'spicy', 'Have you ever been caught talking behind someone''s back?', 'friends'),
('truth', 'spicy', 'What''s a secret crush you''ve never admitted?', 'friends'),
('truth', 'spicy', 'Have you ever pretended to like someone to avoid hurting their feelings?', 'friends'),
('truth', 'spicy', 'What''s the worst thing you''ve done on a dare?', 'friends'),
('truth', 'spicy', 'Have you ever faked being sick to get out of something important?', 'friends'),
('truth', 'spicy', 'What''s the most embarrassing thing on your phone?', 'friends'),
('truth', 'spicy', 'Have you ever cheated in a relationship?', 'friends'),
('truth', 'spicy', 'What''s something illegal you''ve done?', 'friends'),
('truth', 'spicy', 'Have you ever been in trouble with the law?', 'friends'),
('truth', 'spicy', 'What''s the wildest thing you''ve done at a party?', 'friends'),
('truth', 'spicy', 'Have you ever had a crush on a teacher or authority figure?', 'friends'),
('truth', 'spicy', 'What''s a secret you wish you could tell the world?', 'friends'),
('truth', 'spicy', 'Have you ever lied to get out of a date?', 'friends'),
('truth', 'spicy', 'What''s the most embarrassing thing your parents don''t know about you?', 'friends'),
('truth', 'spicy', 'Have you ever stolen something?', 'friends'),
('truth', 'spicy', 'What''s the biggest lie you''ve told?', 'friends'),
('truth', 'spicy', 'Have you ever ghosted someone without explanation?', 'friends'),
('truth', 'spicy', 'What''s the worst secret you''re keeping right now?', 'friends'),
('truth', 'spicy', 'Have you ever been caught doing something inappropriate?', 'friends'),
('truth', 'spicy', 'What''s the meanest thing you''ve ever said to someone?', 'friends'),
('truth', 'spicy', 'Have you ever flirted with someone just to make another jealous?', 'friends'),
('truth', 'spicy', 'What''s the most desperate thing you''ve done for attention?', 'friends'),
('truth', 'spicy', 'Have you ever been embarrassed by your behavior while drunk?', 'friends'),
('truth', 'spicy', 'What''s the weirdest thing you''ve done when no one was watching?', 'friends'),
('truth', 'spicy', 'Have you ever dated someone you didn''t like just for fun?', 'friends'),
('truth', 'spicy', 'What''s a secret you wish no one knew?', 'friends'),
('truth', 'spicy', 'Have you ever snooped through someone''s things?', 'friends'),
('truth', 'spicy', 'What''s the most scandalous thing you''ve done?', 'friends'),
('truth', 'spicy', 'Have you ever lied during Truth or Dare before?', 'friends'),
('truth', 'spicy', 'What''s the worst rumor you''ve heard about yourself?', 'friends'),
('truth', 'spicy', 'Have you ever lied about being sick to avoid something?', 'friends'),
('truth', 'spicy', 'What''s a sexual fantasy you''re afraid to admit?', 'friends'),
('truth', 'spicy', 'Have you ever watched something you''re embarrassed to admit?', 'friends'),
('truth', 'spicy', 'What''s the worst date you''ve ever been on?', 'friends'),
('truth', 'spicy', 'Have you ever lied about your relationship status?', 'friends'),
('truth', 'spicy', 'What''s your most embarrassing drunk story?', 'friends');
