-- Seed data for Truth or Dare questions
-- Run this after schema.sql

-- MILD TRUTHS
INSERT INTO truth_or_dare_questions (type, spice_level, content, points) VALUES
('truth', 'mild', 'What is your biggest fear?', 10),
('truth', 'mild', 'What is your most embarrassing moment?', 10),
('truth', 'mild', 'Who was your first crush?', 10),
('truth', 'mild', 'What is your biggest pet peeve?', 10),
('truth', 'mild', 'What is something you are really bad at?', 10),
('truth', 'mild', 'What is your guilty pleasure?', 10),
('truth', 'mild', 'What is the worst gift you have ever received?', 10),
('truth', 'mild', 'What is your most used emoji?', 10),
('truth', 'mild', 'What is the last lie you told?', 10),
('truth', 'mild', 'What is your biggest regret?', 10),
('truth', 'mild', 'What is something you wish you were better at?', 10),
('truth', 'mild', 'What is your favorite childhood memory?', 10),
('truth', 'mild', 'What is the weirdest food combination you enjoy?', 10),
('truth', 'mild', 'What is your most irrational fear?', 10),
('truth', 'mild', 'What is something you pretend to like but actually hate?', 10),
('truth', 'mild', 'What is the most childish thing you still do?', 10),
('truth', 'mild', 'What is your worst habit?', 10),
('truth', 'mild', 'What is something you are secretly proud of?', 10),
('truth', 'mild', 'What is the longest you have gone without showering?', 10),
('truth', 'mild', 'What is your most unpopular opinion?', 10);

-- MILD DARES
INSERT INTO truth_or_dare_questions (type, spice_level, content, points) VALUES
('dare', 'mild', 'Do your best impression of a celebrity', 10),
('dare', 'mild', 'Speak in an accent for the next 3 rounds', 10),
('dare', 'mild', 'Do 10 pushups', 10),
('dare', 'mild', 'Sing the chorus of your favorite song', 10),
('dare', 'mild', 'Do your best dance move', 10),
('dare', 'mild', 'Tell a joke (it can be bad)', 10),
('dare', 'mild', 'Show the last photo in your camera roll', 10),
('dare', 'mild', 'Do your best animal impression', 10),
('dare', 'mild', 'Speak only in questions for the next 2 rounds', 10),
('dare', 'mild', 'Do a cartwheel or attempt one', 10),
('dare', 'mild', 'Recite a poem or make one up on the spot', 10),
('dare', 'mild', 'Do your best evil laugh', 10),
('dare', 'mild', 'Pretend to be a news anchor and report on your day', 10),
('dare', 'mild', 'Do your best robot dance', 10),
('dare', 'mild', 'Speak in rhymes for the next 2 rounds', 10),
('dare', 'mild', 'Do 20 jumping jacks', 10),
('dare', 'mild', 'Make up a short rap about your friend', 10),
('dare', 'mild', 'Do your best model walk', 10),
('dare', 'mild', 'Pretend to be a waiter and take an imaginary order', 10),
('dare', 'mild', 'Do your best opera singing', 10);

-- SPICY TRUTHS
INSERT INTO truth_or_dare_questions (type, spice_level, content, points) VALUES
('truth', 'spicy', 'What is the most trouble you have ever been in?', 15),
('truth', 'spicy', 'What is your biggest secret?', 15),
('truth', 'spicy', 'Have you ever cheated on a test?', 15),
('truth', 'spicy', 'What is the most embarrassing thing in your search history?', 15),
('truth', 'spicy', 'Have you ever lied to get out of trouble?', 15),
('truth', 'spicy', 'What is something you have done that you would never tell your parents?', 15),
('truth', 'spicy', 'Have you ever had a crush on a friend''s partner?', 15),
('truth', 'spicy', 'What is the worst thing you have said about someone behind their back?', 15),
('truth', 'spicy', 'Have you ever stolen anything?', 15),
('truth', 'spicy', 'What is your most toxic trait?', 15),
('truth', 'spicy', 'Have you ever ghosted someone?', 15),
('truth', 'spicy', 'What is the biggest lie you have ever told?', 15),
('truth', 'spicy', 'Have you ever pretended to be sick to get out of something?', 15),
('truth', 'spicy', 'What is something you judge people for?', 15),
('truth', 'spicy', 'Have you ever spread a rumor?', 15),
('truth', 'spicy', 'What is the most rebellious thing you have ever done?', 15),
('truth', 'spicy', 'Have you ever lied about your age?', 15),
('truth', 'spicy', 'What is something you have done that you are ashamed of?', 15),
('truth', 'spicy', 'Have you ever read someone''s messages without permission?', 15),
('truth', 'spicy', 'What is the worst date you have ever been on?', 15);

-- SPICY DARES
INSERT INTO truth_or_dare_questions (type, spice_level, content, points) VALUES
('dare', 'spicy', 'Text your crush or send them a message right now', 15),
('dare', 'spicy', 'Post an embarrassing photo on social media', 15),
('dare', 'spicy', 'Let the other player read your last 5 text messages', 15),
('dare', 'spicy', 'Call a random contact and sing them a song', 15),
('dare', 'spicy', 'Do a dramatic reading of your last social media post', 15),
('dare', 'spicy', 'Let the other player post anything on your social media', 15),
('dare', 'spicy', 'Show your most embarrassing photo', 15),
('dare', 'spicy', 'Eat a spoonful of a condiment of the other player''s choice', 15),
('dare', 'spicy', 'Do your best impression of the other player', 15),
('dare', 'spicy', 'Let the other player go through your phone for 1 minute', 15),
('dare', 'spicy', 'Send a weird message to a random contact', 15),
('dare', 'spicy', 'Do 30 seconds of your most embarrassing dance', 15),
('dare', 'spicy', 'Let the other player draw on your face', 15),
('dare', 'spicy', 'Speak in a baby voice for the next 3 rounds', 15),
('dare', 'spicy', 'Do your best seductive look at the camera', 15),
('dare', 'spicy', 'Reenact your most embarrassing moment', 15),
('dare', 'spicy', 'Let the other player choose your profile picture for 24 hours', 15),
('dare', 'spicy', 'Do your worst pickup line', 15),
('dare', 'spicy', 'Pretend to be on a reality TV show for the next 2 rounds', 15),
('dare', 'spicy', 'Do your best dramatic movie scene', 15);

-- EXTREME TRUTHS
INSERT INTO truth_or_dare_questions (type, spice_level, content, points) VALUES
('truth', 'extreme', 'What is your deepest, darkest secret?', 20),
('truth', 'extreme', 'Have you ever had feelings for someone in this call?', 20),
('truth', 'extreme', 'What is the most illegal thing you have ever done?', 20),
('truth', 'extreme', 'What is something you would never want your parents to know?', 20),
('truth', 'extreme', 'Have you ever betrayed a friend''s trust?', 20),
('truth', 'extreme', 'What is your most controversial opinion?', 20),
('truth', 'extreme', 'Have you ever been in love with two people at once?', 20),
('truth', 'extreme', 'What is the worst thing you have ever said to someone?', 20),
('truth', 'extreme', 'Have you ever sabotaged someone?', 20),
('truth', 'extreme', 'What is something you have done that could ruin your reputation?', 20),
('truth', 'extreme', 'Have you ever lied about something serious?', 20),
('truth', 'extreme', 'What is your most shameful moment?', 20),
('truth', 'extreme', 'Have you ever manipulated someone?', 20),
('truth', 'extreme', 'What is something you would never admit in person?', 20),
('truth', 'extreme', 'Have you ever done something you knew would hurt someone?', 20),
('truth', 'extreme', 'What is the biggest secret you are keeping from someone?', 20),
('truth', 'extreme', 'Have you ever faked something to impress someone?', 20),
('truth', 'extreme', 'What is something you have done that you would deny if accused?', 20),
('truth', 'extreme', 'Have you ever had a secret that could hurt multiple people?', 20),
('truth', 'extreme', 'What is the most selfish thing you have ever done?', 20);

-- EXTREME DARES
INSERT INTO truth_or_dare_questions (type, spice_level, content, points) VALUES
('dare', 'extreme', 'Confess a secret you have never told anyone', 20),
('dare', 'extreme', 'Call your ex or someone you have not talked to in years', 20),
('dare', 'extreme', 'Post "I lost a bet" on all your social media', 20),
('dare', 'extreme', 'Let the other player send a message to anyone in your contacts', 20),
('dare', 'extreme', 'Delete your most recent social media post', 20),
('dare', 'extreme', 'Tell the other player something you have never told anyone', 20),
('dare', 'extreme', 'Show your bank account balance', 20),
('dare', 'extreme', 'Let the other player look through your entire camera roll', 20),
('dare', 'extreme', 'Call a random number and try to have a 2-minute conversation', 20),
('dare', 'extreme', 'Post an embarrassing childhood photo', 20),
('dare', 'extreme', 'Let the other player read your diary or notes app', 20),
('dare', 'extreme', 'Reveal your biggest insecurity', 20),
('dare', 'extreme', 'Send a risky text to someone you like', 20),
('dare', 'extreme', 'Let the other player control your social media for 10 minutes', 20),
('dare', 'extreme', 'Admit something you have been too scared to say', 20),
('dare', 'extreme', 'Show your most embarrassing DMs', 20),
('dare', 'extreme', 'Let the other player ask you any question and answer 100% honestly', 20),
('dare', 'extreme', 'Post a video of yourself doing something embarrassing', 20),
('dare', 'extreme', 'Tell the other player your most embarrassing fantasy', 20),
('dare', 'extreme', 'Let the other player see your screen time report', 20);
